# Copyright (C) 2018-2020 Lienol <lawlienol@gmail.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#
# Improve by xiaozhuai <xiaozhuai7@gmail.com>
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for FileBrowser
LUCI_DEPENDS:=+luci-compat


include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
