include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-torui
PKG_VERSION:=1.01
PKG_RELEASE:=0

LUCI_TITLE:=Luci Tor UI
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+tor

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
