#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete luci.@command[-1]
	add luci command
	set luci.@command[-1].name='Change Mac'
	set luci.@command[-1].command='sh /etc/config/shell/ch_mac.sh'
	set luci.@command[-1].param=1
	set luci.@command[-1].public=1
	commit luci
EOF
fi

exit 0
